[project]
name = "gitbruv"

[[services]]
name = "web"
path = "apps/web"
startCmd = "bun start:web"
buildCmd = "bun build:web"
port = 3000

[[services]]
name = "api"
path = "apps/api"
startCmd = "bun start:api"
buildCmd = "bun build:api"
port = 3001